#!/usr/bin/env sh
set -e

DOCKER_IMAGE_TAG="${DOCKER_IMAGE_TAG:-dev}"
DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME:-xmtp/bot-examples}"
GIT_COMMIT="$(git rev-parse HEAD)"
TAG="${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"

docker buildx build \
    --platform linux/amd64 \
    --tag "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" \
    --build-arg="GIT_COMMIT=${GIT_COMMIT}" \
    -f dev/docker/examples.Dockerfile \
    -q \
    --push \
    .

